# Generated by Django 4.2.30 on 2026-05-08 03:34

import apps.domains.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SendingDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=255)),
                ('verified', models.BooleanField(default=False)),
                ('verification_token', models.CharField(default=apps.domains.models.generate_verification_token, editable=False, help_text='TXT record value to prove ownership', max_length=64)),
                ('spf_record', models.TextField(blank=True, help_text="Complete SPF TXT record (e.g., 'v=spf1 include:spf.example.com ~all')")),
                ('dkim_selector', models.CharField(default='default', help_text="DKIM selector prefix (e.g., 'google')", max_length=64)),
                ('dkim_private_key', models.TextField(blank=True, help_text='DKIM private key in PEM format (store encrypted in production)')),
                ('dkim_public_key', models.TextField(blank=True, help_text='DKIM public key in PEM format')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'domain_name')},
            },
        ),
    ]
